baseURL: https://www.example.com/
languageCode: en-us
title: Dascot Limited
theme: hugo-hero-theme
module:
  hugoVersion:
    extended: yes
    min: 0.92.0
params:
  google_analytics_id: ''
  homepage_meta_tags:
    meta_description: Data driven solutions for conservations in East Africa.
    meta_og_description: Data driven solutions for conservations in East Africa.
    meta_og_image: https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png
    meta_og_title: Dascot Limited
    meta_og_type: website
    meta_og_url: https://hugo-hero.netlify.app
    meta_twitter_card: summary
    meta_twitter_creator: '@zerostaticio'
    meta_twitter_site: '@zerostaticio'
  logo:
    alt: Hugo Hero
    desktop: images/logo.PNG
    desktop_height: 29px
    desktop_width: 217px
    mobile: images/logo.PNG
    mobile_height: 36px
    mobile_width: 36px
menu:
  main:
    - name: Services
      url: /services/
      weight: 1
    - name: Work
      url: /work/
      weight: 2
    - name: About
      url: /about/
      weight: 3
    - name: Research Portfolio
      url: /history/
      weight: 3
    - name: Contact
      url: /contact/
      weight: 4
permalinks:
  pages: /:filename/
  post: /:year/:month/:day/:slug/
